name: deploy

on:
  push:
    branches:
      - main


jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd server
            git reset --hard
            git fetch
            git pull
            chmod +x gradlew
            ./gradlew clean bootjar
            pm2 stop server
            pm2 delete server
            pm2 start java --name "server" -- -jar build/libs/demo-0.0.1-SNAPSHOT.jar
